import type { SpecialProduct } from "~/types/SpecialProduct";
export function useFetchData() {
  // act as getting data from api url

  const PopurlaProducts: SpecialProduct[] = [
    {
      id: 1,
      name: "WHEY PROTIEN OREO 1.5k",
      price: 100,
      imgs: [
        "/_nuxt/assets/imges/products/WheyPortain/Picsart_24-01-26_06-54-21-965.png",
        "/_nuxt/assets/imges/products/WheyPortain/IMG_20240221_020330-768x947.png",
      ],
      category: "WheyProtain",
      details: "Lorem ipsum is placeholder text commonly used in the graphic.",
      isHot: false,
      selected: false,
      OnSale: true,
      InStock: false,
      offer: false,
      quickview: false,
      compare: false,
      wishlist: false,
      icons: {
        quickview: false,
        compare: false,
        wishlist: false,
        cart: false,
      },
      cartQuanity: 0,
      next: { name: "BULK GAINER MANGO", category: "WeightGainerCarbs" },
      prev: {
        name: "BULK GAINER VANILLA 4KG",
        category: "WeightGainerCarbs",
      },
    },
    {
      id: 2,
      name: "CASEIN PROTEIN STRWPERRY",
      price: 1250,
      imgs: [
        "/_nuxt/assets/imges/products/WheyPortain/IMG_20240126_055846.png",
        "/_nuxt/assets/imges/products/WheyPortain/IMG_20240208_160203.png",
        "/_nuxt/assets/imges/products/WheyPortain/1-e1676102590559-1192x1536.png",
      ],
      category: "WheyProtain",
      details: "Lorem ipsum is placeholder text commonly used in the graphic.",
      isHot: false,
      OnSale: true,
      InStock: true,
      offer: "-50%",

      quickview: false,
      compare: false,
      selected: false,
      wishlist: false,
      icons: {
        quickview: false,
        compare: false,
        wishlist: false,
        cart: false,
      },
      cartQuanity: 0,
      next: {
        name: "CARBO GAINER STRAWPERRY 1kg",
        category: "WeightGainerCarbs",
      },
      prev: {
        name: "HANDLITING",
        category: "Accessories",
      },
    },
    {
      id: 3,
      name: "WHEY OREO 1kg",
      price: 1500,
      imgs: [
        "/_nuxt/assets/imges/products/WheyPortain/IMG_20240126_055056-700x1013.png",
        "/_nuxt/assets/imges/products/WheyPortain/IMG_20230306_021505-860x982.png",
        "/_nuxt/assets/imges/products/WheyPortain/1-e1676102590559-1192x1536.png",
      ],
      category: "WheyProtain",
      details: "Lorem ipsum is placeholder text commonly used in the graphic.",
      isHot: false,
      OnSale: true,
      InStock: true,
      offer: "-1%",

      quickview: false,
      compare: false,
      selected: false,
      wishlist: false,
      icons: {
        quickview: false,
        compare: false,
        wishlist: false,
        cart: false,
      },
      cartQuanity: 0,
      next: {
        name: "RUSH PUMP WATERMELON 30 SERVING",
        category: "PreWorkout",
      },
      prev: {
        name: "CARBO GAINER WATERMELON 1kg",
        category: "WeightGainerCarbs",
      },
    },
    {
      id: 4,
      name: "CASEIN PROTEIN CHOCOLATE",
      price: 1800,
      imgs: [
        "/_nuxt/assets/imges/products/WheyPortain/IMG_20240126_061031.png",
        "/_nuxt/assets/imges/products/WheyPortain/IMG_20240208_160218-768x1032.png",
        "/_nuxt/assets/imges/products/WheyPortain/IMG_20240208_160218-768x1032.png",
        "/_nuxt/assets/imges/products/WheyPortain/IMG_20240208_160218-768x1032.png",
      ],
      category: "WheyProtain",
      details: "Lorem ipsum is placeholder text commonly used in the graphic.",
      isHot: false,
      OnSale: true,
      InStock: true,
      offer: false,

      quickview: false,
      compare: false,
      selected: false,
      wishlist: false,
      icons: {
        quickview: false,
        compare: false,
        wishlist: false,
        cart: false,
      },
      cartQuanity: 0,
      next: {
        name: "BULK GAINER CHOCOLATE ICE CREAM 4KG",
        category: "WeightGainerCarbs",
      },
      prev: {
        name: "CARPOTINE STRAWPERRY 1.5kg",
        category: "WeightGainerCarbs",
      },
    },
    {
      id: 5,
      name: "WHEY PROTIEN STRWPERRY 1.5kg",
      price: 1000,
      imgs: [
        "/_nuxt/assets/imges/products/WheyPortain/Picsart_24-01-26_07-02-43-283.png",
        "/_nuxt/assets/imges/products/WheyPortain/IMG_20240208_160203.png",
        "/_nuxt/assets/imges/products/WheyPortain/1-e1676102590559-1192x1536.png",
      ],
      category: "WheyProtain",
      details: "Lorem ipsum is placeholder text commonly used in the graphic.",
      isHot: false,
      OnSale: true,
      InStock: true,
      offer: false,

      quickview: false,
      compare: false,
      selected: false,
      wishlist: false,
      icons: {
        quickview: false,
        compare: false,
        wishlist: false,
        cart: false,
      },
      cartQuanity: 0,
      next: {
        name: "CREATINE MONOHYDRATE 30 SERVING",
        category: "Creatine",
      },
      prev: {
        name: "CREATINE MONOHYDRATE 60 SERVING",
        category: "Creatine",
      },
    },
    {
      id: 6,
      name: "WHEY STROPERRY CHEESE CAKE 1kg",
      price: 2500,
      imgs: [
        "/_nuxt/assets/imges/products/WheyPortain/IMG_20240126_054636.png",
        "/_nuxt/assets/imges/products/WheyPortain/IMG_20240208_160203.png",
        "/_nuxt/assets/imges/products/WheyPortain/1-e1676102590559-1192x1536.png",
      ],
      category: "WheyProtain",
      details: "Lorem ipsum is placeholder text commonly used in the graphic.",
      isHot: false,
      OnSale: true,
      InStock: true,
      offer: false,

      quickview: false,
      compare: false,
      selected: false,
      wishlist: false,
      icons: {
        quickview: false,
        compare: false,
        wishlist: false,
        cart: false,
      },
      cartQuanity: 0,
      next: { name: "SHAKER 70ML", category: "Accessories" },
      prev: { name: "LIFTING LETING", category: "Accessories" },
    },
    {
      id: 1,
      name: "CITRULLINE MALATE 60 SERVING",
      price: 750,
      imgs: [
        "/_nuxt/assets/imges/products/PreWorkout/Picsart_24-02-23_21-50-20-117-621x800 (1).png",
        "/_nuxt/assets/imges/products/PreWorkout/Picsart_24-04-26_05-04-39-687-860x1290.png",
        "/_nuxt/assets/imges/products/PreWorkout/Picsart_24-04-26_05-04-39-687-860x1290.png",
      ],
      category: "PreWorkout",
      details: "Lorem ipsum is placeholder text commonly used in the graphic.",
      isHot: true,
      OnSale: true,
      InStock: true,
      offer: "-7%",
      quickview: false,
      compare: false,
      selected: false,
      wishlist: false,
      icons: {
        quickview: false,
        compare: false,
        wishlist: false,
        cart: false,
      },
      cartQuanity: 0,
      next: { name: "HANDLITING", category: "Accessories" },
      prev: {
        name: "RUSH PUMP WATERMELON 30 SERVING",
        category: "PreWorkout",
      },
    },
    {
      id: 2,
      name: "BETA-ALANINE 60 SERVING",
      price: 800,
      imgs: [
        "/_nuxt/assets/imges/products/PreWorkout/Picsart_24-02-23_22-09-52-372.png",
        "/_nuxt/assets/imges/products/PreWorkout/Picsart_24-04-25_03-10-14-212-1.png",
      ],
      category: "PreWorkout",
      details: "Lorem ipsum is placeholder text commonly used in the graphic.",
      isHot: true,
      OnSale: true,
      InStock: true,
      offer: "-7%",
      quickview: false,
      compare: false,
      selected: false,
      wishlist: false,
      icons: {
        quickview: false,
        compare: false,
        wishlist: false,
        cart: false,
      },
      cartQuanity: 0,
      next: {
        name: "RUSH PUMP LEMON MINT 30 SERVING",
        category: "PreWorkout",
      },
      prev: {
        name: "CITRULLINE MALATE 60 SERVING",
        category: "PreWorkout",
      },
    },
  ];
  const data = ref<SpecialProduct[]>(PopurlaProducts);

  return data.value;
}
